version : '3.9'

services:
  redis:
    image: redis
    hostname: ${REDIS_HOST}
    container_name: redis_container
    restart: on-failure
    command: redis-server --requirepass ${REDIS_PASSWORD} --port ${REDIS_PORT}
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      REDIS_PORT: ${REDIS_PORT}
    volumes:
      - ./redis.conf:/usr/local/etc/redis.conf
    networks:
      - account_network

  accounts:
    build: .
    container_name: account_container
    hostname: ${ACCOUNT_HOST}
    image: ${ACCOUNT_HOST}
    ports:
      - ${DJANGO_PORT}:${DJANGO_PORT}   
    restart: on-failure
    volumes:
      - .:/accounts
    command: sh -c "python3 manage.py makemigrations && 
                    python3 manage.py migrate --no-input && 
                    python3 manage.py collectstatic --no-input && 
                    gunicorn -k gevent --workers 4 config.wsgi:application -b 0.0.0.0:${DJANGO_PORT}"
    depends_on:
      - redis
      - keycloak
      - postgres
    env_file:
      - .env
    links: 
      - redis
    networks:
      - account_network
      - keycloak_network

  celery-worker:
    build: .
    container_name: celery_worker_container
    hostname: celery_worker
    command: bash -c " celery -A config worker -l info "
    restart: on-failure
    depends_on:
      - accounts
      - redis
    image: celery_account_image
    volumes:
      - .:/accounts
    links: 
      - redis
    networks:
      - account_network


networks:
  account_network:
  keycloak_network:
    external: true
