services:
  postgres:
    image: postgres
    hostname: ${POSTGRES_HOST}
    container_name: postgres_keycloak
    restart: on-failure
    environment: 
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    env_file:
      - .env
    expose:
      - ${POSTGRES_PORT}
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
#    volumes:
#      - ./data/postgres:/var/lib/postgresql/data
    networks: 
      - keycloak_network


  keycloak:
    image: quay.io/keycloak/keycloak:26.0.6
    hostname: ${KEYCLOAK_HOST}
    container_name: keycloak_container
    command: start-dev
    environment:
      - KEYCLOAK_ADMIN=${KEYCLOAK_ADMIN}
      - KEYCLOAK_ADMIN_PASSWORD=${KEYCLOAK_ADMIN_PASSWORD}
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://postgres/${POSTGRES_DB}
      - KC_DB_USERNAME=${POSTGRES_USER}
      - KC_DB_PASSWORD=${POSTGRES_PASSWORD}
    depends_on:
      - postgres
    volumes:
      - ./data/keycloak-data:/opt/keycloak/data
    ports:
      - ${KEYCLOAK_PORT}:${KEYCLOAK_PORT}
    networks:
      - keycloak_network


networks:
  keycloak_network:
    driver: bridge
    name: keycloak_network
